name: build

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/mrsupiri/kube-ebpf
  DOCKER_BUILDKIT: 1

jobs:
  kube-ebpf:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t $IMAGE_NAME:latest .
      - run: docker tag $IMAGE_NAME:latest $IMAGE_NAME:commit-${GITHUB_SHA:0:8}
      - run: docker push $IMAGE_NAME --all-tags
  init-headers:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: init-headers
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t $IMAGE_NAME/init-headers:latest .
      - run: docker tag $IMAGE_NAME/init-headers:latest $IMAGE_NAME/init-headers:commit-${GITHUB_SHA:0:8}
      - run: docker push $IMAGE_NAME/init-headers --all-tags